package com.siarex247.cumplimientoFiscal.Conciliacion;



public class ConciliacionQuerys {

	
	private static String detalleConSinComple =  "select  P.RFC, P.RAZON_SOCIAL, A.FOLIO_ORDEN, A.FOLIO_EMPRESA, A.TIPO_MONEDA, A.SERIE, A.FECHAPAGO,  C.FECHA_PAGO, C.FECHA_TIMBRADO, A.UUID, A.SUB_TOTAL, A.IVA, A.IVA_RET, A.IMP_LOCALES, A.TOTAL, C.UUID_COMPLEMENTO, C.TOTAL_PAGADO, C.TOTAL_COMPLEMENTO, A.ESTATUS_SAT, C.ESTATUS_COMPLEMENTO, C.NOMBRE_XML, C.NOMBRE_PDF, C.ESTATUS_CONCILIACION, P.CLAVE_PROVEEDOR, A.TIPO_ORDEN from ORDENES A inner join PROVEEDORES P on A.CLAVE_PROVEEDOR = P.CLAVE_PROVEEDOR left join COMPLEMENTARIA C on A.FOLIO_EMPRESA = C.FOLIO_EMPRESA  where A.ESTATUS_PAGO in ( ?, ? )and A.FECHAPAGO between ? and ? and P.TIPO_PROVEEDOR = ? ";
	private static String detalleConComple    =  "select  P.RFC, P.RAZON_SOCIAL, A.FOLIO_ORDEN, A.FOLIO_EMPRESA, A.TIPO_MONEDA, A.SERIE, A.FECHAPAGO,  C.FECHA_PAGO, C.FECHA_TIMBRADO, A.UUID, A.SUB_TOTAL, A.IVA, A.IVA_RET, A.IMP_LOCALES, A.TOTAL, C.UUID_COMPLEMENTO, C.TOTAL_PAGADO, C.TOTAL_COMPLEMENTO, A.ESTATUS_SAT, C.ESTATUS_COMPLEMENTO, C.NOMBRE_XML, C.NOMBRE_PDF, C.ESTATUS_CONCILIACION, P.CLAVE_PROVEEDOR, A.TIPO_ORDEN from ORDENES A inner join PROVEEDORES P on A.CLAVE_PROVEEDOR = P.CLAVE_PROVEEDOR inner join COMPLEMENTARIA C on A.FOLIO_EMPRESA = C.FOLIO_EMPRESA  where A.ESTATUS_PAGO = ? and A.FECHAPAGO between ? and ? and P.TIPO_PROVEEDOR = ? ";
	//private static String detalleSinComple    =  "select  P.RFC, P.RAZON_SOCIAL, A.FOLIO_ORDEN, A.FOLIO_EMPRESA, A.TIPO_MONEDA, A.SERIE, A.FECHAPAGO,  C.FECHA_PAGO, C.FECHA_TIMBRADO, A.UUID, A.SUB_TOTAL, A.IVA, A.IVA_RET, A.IMP_LOCALES, A.TOTAL, C.UUID_COMPLEMENTO, C.TOTAL_PAGADO, C.TOTAL_COMPLEMENTO, A.ESTATUS_SAT, C.ESTATUS_COMPLEMENTO, C.NOMBRE_XML, C.NOMBRE_PDF, C.ESTATUS_CONCILIACION, P.CLAVE_PROVEEDOR, A.TIPO_ORDEN from ORDENES A inner join PROVEEDORES P on A.CLAVE_PROVEEDOR = P.CLAVE_PROVEEDOR left join COMPLEMENTARIA C on A.FOLIO_EMPRESA = C.FOLIO_EMPRESA  where A.ESTATUS_PAGO = ? and A.FECHAPAGO between ? and ? and P.TIPO_PROVEEDOR = ? and C.FOLIO_ORDEN is NULL "; 
	private static String detalleSinComple    =  "select  P.RFC, P.RAZON_SOCIAL, A.FOLIO_ORDEN, A.FOLIO_EMPRESA, A.TIPO_MONEDA, A.SERIE, A.FECHAPAGO,  NULL as FECHA_PAGO, NULL AS FECHA_TIMBRADO, A.UUID, A.SUB_TOTAL, A.IVA, A.IVA_RET, A.IMP_LOCALES, A.TOTAL, NULL AS UUID_COMPLEMENTO, 0 AS TOTAL_PAGADO, 0 AS TOTAL_COMPLEMENTO, A.ESTATUS_SAT, NULL AS ESTATUS_COMPLEMENTO, NULL AS NOMBRE_XML, NULL AS NOMBRE_PDF, NULL AS ESTATUS_CONCILIACION, P.CLAVE_PROVEEDOR, A.TIPO_ORDEN from ORDENES A inner join PROVEEDORES P on A.CLAVE_PROVEEDOR = P.CLAVE_PROVEEDOR where A.ESTATUS_PAGO = ? and A.FECHAPAGO between ? and ? and P.TIPO_PROVEEDOR = ? ";

	private static String exportarZipConComple    =  "select  C.NOMBRE_XML, C.NOMBRE_PDF, P.CLAVE_PROVEEDOR from ORDENES A inner join PROVEEDORES P on A.CLAVE_PROVEEDOR = P.CLAVE_PROVEEDOR inner join COMPLEMENTARIA C on A.FOLIO_EMPRESA = C.FOLIO_EMPRESA  where A.ESTATUS_PAGO = ? and A.FECHAPAGO between ? and ? and P.TIPO_PROVEEDOR = ? ";
	
	
	public static String getDetalleConSinComple(String esquema) {
		return detalleConSinComple.replaceAll("<<esquema>>", esquema);
	}
	
	
	public static String getDetalleConComple(String esquema) {
		return detalleConComple.replaceAll("<<esquema>>", esquema);
	}

	
	
	public static String getDetalleSinComple(String esquema) {
		return detalleSinComple.replaceAll("<<esquema>>", esquema);
	}
	
	
	public static String getExportarZipConComple(String esquema) {
		return exportarZipConComple.replaceAll("<<esquema>>", esquema);
	}
	
}
